# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

"""

import urllib.request
import requests
import pandas as pd
import json
import xmltodict

!pip install xmltodict

url = 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson'
#key='개인키'
params ={'serviceKey' : key, 'pageNo' : 1, 'numOfRows' : 100, 'startCreateDt' : '20220420', 'endCreateDt' : '20220425' }

response = requests.get(url, params=params)
results = response.text
results

result_to_json = xmltodict.parse(results)
#result_to_json
json_dump = json.dumps(result_to_json)
#json_dump
data = json.loads(json_dump)
data

corona = data['response']['body']['items']['item']
corona

corona[0]['stateDt'], corona[0]['decideCnt'], corona[0]['deathCnt']

sDate = []
cCnt = []
dCnt = []

for n in range(len(corona)-1, -1, -1):
  sDate.append(corona[n]['stateDt'])
  cCnt.append(corona[n]['decideCnt'])
  dCnt.append(corona[n]['deathCnt'])

sDate, cCnt, dCnt

coronaData = ({"기준일":sDate, "확진자수":cCnt, "사망자수":dCnt})
coronaDf = pd.DataFrame(coronaData)

coronaDf

coronaDf.to_excel("corona.xlsx", sheet_name='corona')

coronaDf.info()

coronaDf['기준일'] = pd.to_datetime(coronaDf['기준일'])

coronaDf['사망자수'] = coronaDf['사망자수'].astype('int')

coronaDf['확진자수'] = coronaDf['확진자수'].astype('int')

import matplotlib.pyplot as plt

x = coronaDf['기준일']
y = coronaDf['사망자수']
y1 = coronaDf['확진자수']

plt.plot(x,y)
plt.plot(x,y1)

