# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

"""

address = ['서울시 동작구 상도동', '서울특별시 동작구 사당동']
address[0]

addr = address[0].split()

if addr[0] == '서울시':
  addr[0] = '서울특별시'

addr

stringJoin = 'string'
'A'.join(stringJoin)

' '.join(addr)

import pandas as pd
import folium

file_path = '/content/drive/MyDrive/Colab/CoffeeBean.xlsx'
CB = pd.read_excel(file_path)
CB

CB.drop('Unnamed: 0', axis=1, inplace=True)

CB

CB['address']

addr = []
for address in CB['address']:
  # print(address)
  addr.append(address.split())

addr

addr2 = []
for i in range(len(addr)):
  if addr[i][0] == '서울':
    addr[i][0] = '서울특별시'
  elif addr[i][0] == '서울시':
    addr[i][0] = '서울특별시'
  elif addr[i][0] == '경기':
    addr[i][0] = '경기도'
  elif addr[i][0] == '경남':
    addr[i][0] = '경상남도'
  elif addr[i][0] == '광주':
    addr[i][0] = '광주광역시'
  elif addr[i][0] == '대전시':
    addr[i][0] = '대전광역시'
  elif addr[i][0] == '부산':
    addr[i][0] = '부산광역시'
  elif addr[i][0] == '부산시':
    addr[i][0] = '부산광역시'
  elif addr[i][0] == '인천':
    addr[i][0] = '인천광역시'
  elif addr[i][0] == '인천시':
    addr[i][0] = '인천광역시'
  elif addr[i][0] == '제주도':
    addr[i][0] = '제주특별자치도'
  elif addr[i][0] == '충남':
    addr[i][0] = '충청남도'
  elif addr[i][0] == '충북':
    addr[i][0] = '충청북도'

  addr2.append(' '.join(addr[i]))

addr2

# address의 고유 원소 값 확인
"""addr2 = []
for n in range(len(addr)):
    addr2.append(addr[n][0])"""

# 중복을 허용하지 않는 자료형
# set(addr2)

# id(CB)

CB2 = CB # 동일한 주소 값, 기존 데이터에 손상을 입힐 수 있음
# id(CB2)

CB2 = CB.copy() # copy() 하게 되면 주소 값이 달라짐, 복사
# id(CB2)
CB2['address2'] = addr2 # 리스트 구조
CB2

CB2.drop('address', axis=1, inplace=True)

CB2

CB2.rename(columns={'address2':'address'}, inplace=True)

CB2

CB2.to_csv('/content/drive/MyDrive/Colab/CB2.csv', index=False)

CB3 = pd.read_csv('/content/drive/MyDrive/Colab/CB3.csv')
CB3

map = folium.Map(location = [37.559978, 126.975291], zoom_start=14)

map.save('/content/drive/MyDrive/Colab/map.html')

map_CB3 = folium.Map(location = [37.559978, 126.975291], zoom_start=14)

for i, info in CB3.iterrows():
  folium.Marker(location=[info['Latitude'],info['Longitude']], icon=folium.Icon(color='blue', icon='start')).add_to(map_CB3)

map_CB3.save('/content/drive/MyDrive/Colab/map_CB3.html')