# -*- coding: utf-8 -*-
"""


Automatically generated by Colaboratory.


"""

import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, plot_roc_curve

df=pd.read_csv('/content/drive/MyDrive/Colab/train.csv')

df.head()

df.shape

df.columns

df.columns.values

df['subject'].unique()

df['Activity'].unique()

df['Activity'].value_counts()

plt.figure(figsize=(15, 10))
sns.countplot(x='Activity', data=df)
plt.xticks(x=df['Activity'], rotation=90)
plt.show()

df.groupby('subject')['Activity'].nunique()

#pd.set_option('display.max_row', None)
#pd.reset_option('all')
df.groupby('subject')['Activity'].value_counts()

sns.set_style('whitegrid')
plt.figure(figsize=(20, 10))
sns.countplot(x='subject', hue = 'Activity', data=df)
plt.legend(loc='upper right')
plt.show()

X = df.drop('Activity', axis = 1, inplace = False)
Y = df['Activity']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=156)

y_train

dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

Y_predict = dtc.predict(x_test)

confusion_matrix(y_test, Y_predict)

accuracy_score(y_test, Y_predict)