# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

"""

from bs4 import BeautifulSoup
#import bs4

html ='<html><head><style>.re{text-align: center;text-decoration: underline; color: blue;}</style></head><body><h1 id="title">연구기관 및 대학</h1><div class ="top"><ul class  = "menu"><li><a class="re" href="https://www.nrf.re.kr">한국연구재단</a></li></ul><ul class  = "univ"><li><a  href="http://www.ssu.ac.kr/">숭실대학교</a></li><li><a  href="http://www.snu.ac.kr/">서울대학교</a></li></ul><table align="left" bgcolor="#00ff00"><tr><td>학교명</td><td>주소</td><td>전화번호</td></tr><tr><td>숭실대점</td><td>서울시 동작구 상도로 369</td><td>02-828-9010</td></tr></table></body></html>'
soup = BeautifulSoup(html, 'html.parser')
soup
print(soup.prettify())

soup.h1

soup.table

tag_ul = soup.ul

tag_ul.attrs

tag_ul = soup.find_all('ul')

tag_ul[1]

tag_ul_1 = soup.find('ul')

tag_ul_1

tag_ul_1.string

print(tag_ul[1].string)

tag_li = tag_ul[1].find_all('li')
tag_li

tag_li[0].string

from bs4 import BeautifulSoup
import urllib.request

Hollys_url = 'https://www.hollys.co.kr/store/korea/korStore.do?pageNo=1&sido=&gugun=&store='
Hollys_url

html_response = urllib.request.urlopen(Hollys_url)
html = html_response.read()

html

soupHollys = BeautifulSoup(html, 'html.parser')
print(soupHollys.prettify())

tag_tbody = soupHollys.find('tbody')
tag_tr = tag_tbody.find_all('tr')
tag_td = tag_tr[0].find_all('td')
tag_td

store_name = tag_td[0].string
store_address = tag_td[3].string
store_tel = tag_td[5].string

store_name, store_address, store_tel

import pandas as pd

Hollys_dic = {"매장이름":store_name, "주소":store_address, "전화번호":store_tel}

Hollys_store = pd.DataFrame(Hollys_dic, index=[0])
Hollys_store

